name: FlowBar
options:
  bundleIdPrefix: com.flowbar
  deploymentTarget:
    macOS: "13.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.flowbar.macos
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    DEVELOPMENT_TEAM: ""
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O

targets:
  FlowBar:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources/FlowBar
    preBuildScripts:
      - name: Fetch yt-dlp
        script: scripts/fetch-yt-dlp.sh
        showEnvVars: false
        inputFiles:
          - scripts/fetch-yt-dlp.sh
        outputFiles:
          - Resources/bin/yt-dlp
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/bin/yt-dlp
      - name: Fetch ffmpeg
        script: scripts/fetch-ffmpeg.sh
        showEnvVars: false
        inputFiles:
          - scripts/fetch-ffmpeg.sh
        outputFiles:
          - Resources/bin/ffmpeg
          - Resources/bin/ffprobe
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/bin/ffmpeg
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/bin/ffprobe
      - name: Fetch deno
        script: scripts/fetch-deno.sh
        showEnvVars: false
        inputFiles:
          - scripts/fetch-deno.sh
        outputFiles:
          - Resources/bin/deno
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/bin/deno
    info:
      path: Config/Info.plist
    settings:
      base:
        PRODUCT_NAME: FlowBar
        INFOPLIST_FILE: Config/Info.plist
    dependencies:
      - package: Sparkle
        product: Sparkle
    scheme:
      testTargets:
        - FlowBarUITests
        - FlowBarTests
  FlowBarUITests:
    type: bundle.ui-testing
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Tests/FlowBarUITests
    dependencies:
      - target: FlowBar
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  FlowBarTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Tests/FlowBarTests
    dependencies:
      - target: FlowBar
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.8.1
